### ISSUE TITLE
Doesn't work for electron provider

### ISSUE THREAD

**Issue by joshuef** [DevExpress/testcafe-action#12]
on ubuntu: 

```
ERROR Unable to find the browser. "electron:." is not a browser alias or path to an executable file.

Type "testcafe -h" for help.
child_process.js:660
    throw err;
    ^

Error: Command failed: xvfb-run --server-args="-screen 0 1280x720x24" npx testcafe electron:. ./__testcafe__/*.spec.*
    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at Object.<anonymous> (/home/runner/work/_actions/DevExpress/testcafe-action/latest/index.js:63:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 4357,
  stdout: null,
  stderr: null
}
```

Could this maybe be avoided by not going via `npx` and relying on an installed testcafe? I'm not 100% on github action organisation yet...

**Comment by miherlosev** [comment]
Hi @joshuef 

Could you please provide a full example that we can run locally to find the cause of the issue?
